env:
  TERM: alacritty

window:
  title: Alacritty

  class:
    general: Alacritty
    instance: Alacritty

  opacity: 1

  padding:
    x: 2
    y: 2

font:
  normal:
    family: "FiraCode Nerd Font"
    style: "Regular"

  bold:
    family: "FiraCode Nerd Font"
    style: "Bold"

  italic:
    family: "JetBrainsMono NF"
    style: "Italic"

  bold_italic:
    family: "JetBrainsMono NF"
    style: "Bold Italic"

  size: 6

import:
  - ~/.config/alacritty/nightfox.yml

cursor:
  style: Block
  unfocused_hollow: true
  vi_mode_style: Beam

draw_bold_text_with_bright_colors: true

live_config_reload: true

scrolling:
  history: 10000

selection:
  save_to_clipboard: true
