templates:
  params:
    author-email: gnoel5@bloomberg.net
    category: Misc
    github-username: gnoel
    author-name: Geoffrey Noel
system-ghc: true
install-ghc: false
extra-include-dirs:
- /opt/bb/include
extra-lib-dirs:
- /lib64
- /opt/bb/lib64
package-indices:
- download-prefix: https://bbhackage.dev.bloomberg.com/
  hackage-security:
    keyids:
    - 8024889f106936d5ba6d1650fadb8e1f82ab650ff30ae0a21830d52fd88386b7
    - efe85c7809c76e633acaf742ce974583fbdfb263d51478f87423e90d5aed47d9
    - 034b48bc4d270eaea46a8aa5b529f84dba8a0bf351d9edd40584b9896dc1879f
    key-threshold: 3
hackage-base-url: https://bbhackage.dev.bloomberg.com/
urls:
  latest-snapshot: "https://bbhackage.dev.bloomberg.com/stack/snapshots.json"
